.\" Manpage for javino.
.\" Contact chon@grupo.cefet-rj.br.
.TH man 8 "15 May 2023" "1.6" "javino man page"

.SH NAME
javino \- Javino (http://javino.sf.net)

.SH DESCRIPTION
A library to supports a robotic-agent platform that uses Raspberry+Arduino boards and Jason Framework.

user@computer:$ javino [PORT]
        javino@[PORT]$ [TYPE] [MSG] 

[TYPE] 
 listen  -- wait an answer from Arduino
 request -- send a request to Arduino, wait answer 
 command -- send a command to Arduino, without wait answer

.SH EXAMPLE
javino /dev/ttyACM0
        javino@ttyACM0$ command ledOn 
    Sends <ledOn> command to the ATMEGA microcontroller to run at the actuator.

javino /dev/ttyACM0
        javino@ttyACM0$ request getPercepts 
    Sends a request <getPercept> to the ATMEGA microcontroller to gather perceptions of the sensors.


.SH REPORTING BUGS
Research Group in Cognitive Hardware On Networks: chon@grupo.cefet-rj.br

.SH COPYRIGHT
N. M. Lazarin e C. E. Pantoja, “A robotic-agent platform for embedding software agents using raspberry pi and arduino boards”, in Proceedings of 9th Software Agents, Environments and Applications School (WESAAC 2015), Niteroi: UFF, 2015, p. 13–20. [Online]. Available at: https://www.researchgate.net/publication/277403727_A_Robotic-agent_Platform_for_Embedding_Software_Agents_Using_Raspberry_Pi_and_Arduino_Boards
